Assigment 1
vadymbl/bl_tec_roku pull request #3
Opened 2022-11-12 18:16 UTC by BrandonCR06

2022-11-13 15:56 UTC, vadymbl requested changes

2022-11-13 15:56 UTC, vadymbl commented on components/Tasks/RootCH.brs
> +    url.SetUrl("http://no-cache.s3.us-east-2.amazonaws.com/vyarchych-home/tec/public_vids.json")
Please set https certificates using `SetCertificatesFile` method. If you will try to fetch `https://` link without certificates you will not get response

2022-11-13 15:56 UTC, vadymbl commented on components/Tasks/RootCH.brs
> +    for each video in json["categories"][0]["videos"]
Please use chain operator. `json?["categories"]?[0]?["videos"]`
This operator should be used whenever you want to get value from nested objects. Without this operator, app will crash if there is invalid somewhere in your access chain.

https://developer.roku.com/en-gb/docs/references/brightscript/language/expressions-variables-types.md#optional-chaining-operators

2022-11-13 16:48 UTC, BrandonCR06 commented
Fixed

2022-11-14 14:33 UTC, vadymbl approved these changes

2022-11-14 14:33 UTC, merged