Asignment 1,2,3
vadymbl/bl_tec_roku pull request #4
Opened 2022-11-13 23:23 UTC by Ricardo08-c

Here is how I tried to solve the asignments

2022-11-13 23:40 UTC, Ricardo08-c commented
Here is my solution to the asignments

2022-11-14 15:29 UTC, vadymbl requested changes

2022-11-14 15:29 UTC, vadymbl commented on components/Tasks/RootCH.brs
> +    for each video in response.categories[0].videos
Please use chain operator. json?["categories"]?[0]?["videos"]
This operator should be used whenever you want to get value from nested objects. Without this operator, app will crash if there is invalid somewhere in your access chain.

https://developer.roku.com/en-gb/docs/references/brightscript/language/expressions-variables-types.md#optional-chaining-operators

2022-11-14 15:29 UTC, vadymbl commented on components/Tasks/RootCH.brs
> +    searchRequest = CreateObject("roUrlTransfer")
Please set https certificates using SetCertificatesFile method. If you will try to fetch https:// link without certificates you will not get response

2022-11-21 15:08 UTC, merged