Assignment 5
vadymbl/bl_tec_roku pull request #8
Opened 2022-11-20 03:04 UTC by Ricardo08-c

This is my implementation for the 5th assignment, also I made the recommended changes to the for loop and the certificates.

2022-11-21 15:16 UTC, vadymbl requested changes

2022-11-21 15:16 UTC, vadymbl commented on components/Tasks/RootCH.brs
> +    m.global.addFields({ads:adsArr})
Please save interactive ad in the related video item. Exposing global for this it's bad solution.

2022-11-28 10:44 UTC, Ricardo08-c commented on components/Tasks/RootCH.brs
> +    m.global.addFields({ads:adsArr})
I already pushed the respective changes

2022-11-28 15:08 UTC, vadymbl approved these changes

2022-11-28 15:08 UTC, merged